-- Frozen baseline: preserves existing IDs, constraints and history.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "assignment_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "crew_id" BIGINT,
    "worker_id" BIGINT NOT NULL,
    "work_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "before_subobject_id" BIGINT,
    "after_subobject_id" BIGINT,
    "changed_by" BIGINT NOT NULL,
    "changed_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "assignments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "work_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "subobject_id" BIGINT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "employer" TEXT NOT NULL DEFAULT '',
    "foreman_user_id" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    "crew_id" BIGINT,
    "edit_token" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE "contractors" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    "name_key" TEXT NOT NULL,
    "active" BIGINT NOT NULL DEFAULT 1,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (active IN (0, 1))
);

CREATE TABLE "crew_members" (
    "crew_id" BIGINT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    PRIMARY KEY ("crew_id", "worker_id")
);

CREATE TABLE "crews" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    "owner_user_id" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    "import_key" TEXT,
    "linear_itr" TEXT NOT NULL DEFAULT '',
    "brigadier" TEXT NOT NULL DEFAULT '',
    "details_token" TEXT NOT NULL DEFAULT '',
    "linear_itr_person_id" BIGINT,
    "brigadier_person_id" BIGINT,
    "linear_itr_worker_id" BIGINT,
    "brigadier_worker_id" BIGINT,
    PRIMARY KEY ("id")
);

CREATE TABLE "daily_staffing_plans" (
    "subobject_id" BIGINT NOT NULL,
    "work_date" TEXT NOT NULL,
    "planned_count" BIGINT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    PRIMARY KEY ("subobject_id", "work_date"),
    CHECK (planned_count >= 0)
);

CREATE TABLE "employee_contractors" (
    "worker_id" BIGINT NOT NULL,
    "contractor_id" BIGINT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "employee_employers" (
    "worker_id" BIGINT NOT NULL,
    "employer" TEXT NOT NULL,
    "source_employer" TEXT,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "employee_gdlr" (
    "worker_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "employee_removals" (
    "worker_id" BIGINT NOT NULL,
    "effective_date" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "changed_by" BIGINT NOT NULL,
    "changed_at" TEXT NOT NULL,
    "worker_name" TEXT NOT NULL,
    "personnel_no" TEXT NOT NULL,
    "crew_id" BIGINT,
    "crew_name" TEXT NOT NULL,
    "actor_name" TEXT NOT NULL,
    "actor_username" TEXT NOT NULL,
    "removed_assignments_json" TEXT NOT NULL,
    PRIMARY KEY ("worker_id"),
    CHECK (LENGTH(TRIM(reason)) BETWEEN 1 AND 1000)
);

CREATE TABLE "employee_restorations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "restored_date" TEXT NOT NULL,
    "changed_at" TEXT NOT NULL,
    "changed_by" BIGINT NOT NULL,
    "worker_name" TEXT NOT NULL,
    "personnel_no" TEXT NOT NULL,
    "crew_id" BIGINT,
    "crew_name" TEXT NOT NULL,
    "actor_name" TEXT NOT NULL,
    "actor_username" TEXT NOT NULL,
    "removal_json" TEXT,
    "edit_token" TEXT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (removal_json IS NULL OR JSON_VALID(removal_json))
);

CREATE TABLE "employee_smu" (
    "worker_id" BIGINT NOT NULL,
    "smu_id" BIGINT NOT NULL,
    "source_department" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "gdlr_categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    "name_key" TEXT NOT NULL,
    "active" BIGINT NOT NULL DEFAULT 1,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "staffing_allowed" BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CHECK (active IN (0, 1)),
    CHECK (staffing_allowed IN (0, 1))
);

CREATE TABLE "location_revisions" (
    "kind" TEXT NOT NULL,
    "location_id" BIGINT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("kind", "location_id"),
    CHECK (kind IN ('objects', 'subobjects'))
);

CREATE TABLE "location_stages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" CITEXT NOT NULL,
    "edit_token" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE "manual_employees" (
    "worker_id" BIGINT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    "qualification" TEXT NOT NULL DEFAULT '',
    "request_key" TEXT NOT NULL,
    "payload_hash" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "manual_staffing_people" (
    "person_id" BIGINT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("person_id")
);

CREATE TABLE "objects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" CITEXT NOT NULL,
    "stage_id" BIGINT,
    PRIMARY KEY ("id")
);

CREATE TABLE "outstaff_import_rows" (
    "import_id" BIGINT NOT NULL,
    "source_row" BIGINT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "source_json" TEXT NOT NULL,
    "mapping_json" TEXT NOT NULL,
    PRIMARY KEY ("import_id", "source_row")
);

CREATE TABLE "outstaff_imports" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "request_key" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "sheet" TEXT NOT NULL,
    "file_hash" TEXT NOT NULL,
    "selection_json" TEXT NOT NULL,
    "imported_by" BIGINT NOT NULL,
    "imported_at" TEXT NOT NULL,
    "selected_count" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "outstaff_members" (
    "worker_id" BIGINT NOT NULL,
    "identity_key" TEXT NOT NULL,
    "import_id" BIGINT NOT NULL,
    "source_row" BIGINT NOT NULL,
    "source_department" TEXT NOT NULL,
    "source_category" TEXT NOT NULL,
    "work_kind" TEXT NOT NULL,
    "vendor" TEXT NOT NULL,
    "staff_type" TEXT NOT NULL,
    "arrival" TEXT NOT NULL,
    "departure" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "placement_verification_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "assignment_id" BIGINT NOT NULL,
    "work_date" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "snapshot_json" TEXT NOT NULL,
    "changed_by" BIGINT NOT NULL,
    "changed_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "placement_verifications" (
    "assignment_id" BIGINT NOT NULL,
    "work_date" TEXT NOT NULL,
    "fingerprint" TEXT NOT NULL,
    "verified_by" BIGINT NOT NULL,
    "verified_at" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    PRIMARY KEY ("assignment_id")
);

CREATE TABLE "schema_versions" (
    "version" BIGINT NOT NULL,
    PRIMARY KEY ("version")
);

CREATE TABLE "smu_aliases" (
    "name" TEXT NOT NULL,
    "smu_id" BIGINT NOT NULL,
    PRIMARY KEY ("name")
);

CREATE TABLE "smu_catalog" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    "active" BIGINT NOT NULL DEFAULT 1,
    "edit_token" TEXT NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'),
    "updated_by" BIGINT,
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "site_chief_user_id" BIGINT,
    PRIMARY KEY ("id"),
    CHECK (active IN (0, 1))
);

CREATE TABLE "staffing_action_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "label" TEXT NOT NULL,
    "work_date" TEXT NOT NULL,
    "scope_json" TEXT NOT NULL,
    "changes_json" TEXT NOT NULL,
    "guards_json" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (state IN ('done', 'undone', 'discarded'))
);

CREATE TABLE "staffing_attendance" (
    "work_date" TEXT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("work_date", "worker_id"),
    CHECK (status IN ('Явка', 'Вых', 'Без сод', 'Больн', 'МО'))
);

CREATE TABLE "staffing_day_inheritance" (
    "work_date" TEXT NOT NULL,
    "scope_key" TEXT NOT NULL,
    "source_date" TEXT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("work_date", "scope_key")
);

CREATE TABLE "staffing_history_replays" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "action_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "direction" TEXT NOT NULL,
    "changed_at" TEXT NOT NULL,
    "backup_name" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "staffing_import_members" (
    "import_id" BIGINT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "source_row" BIGINT NOT NULL,
    "source_crew" TEXT NOT NULL,
    PRIMARY KEY ("import_id", "worker_id")
);

CREATE TABLE "staffing_imports" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "sha256" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "imported_by" BIGINT NOT NULL,
    "imported_at" TEXT NOT NULL,
    "selected_count" BIGINT NOT NULL,
    "summary_json" TEXT NOT NULL,
    "source_label" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE TABLE "staffing_inherited_rows" (
    "work_date" TEXT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "source_date" TEXT NOT NULL,
    "snapshot_json" TEXT NOT NULL,
    PRIMARY KEY ("work_date", "worker_id")
);

CREATE TABLE "staffing_people" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "import_id" BIGINT NOT NULL,
    "source_row" BIGINT NOT NULL,
    "full_name" TEXT NOT NULL,
    "personnel_no" TEXT NOT NULL,
    "profession" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "qualification" TEXT NOT NULL,
    "source_crew" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "staffing_performed_work" (
    "work_date" TEXT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "shift" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("work_date", "worker_id", "shift"),
    CHECK (shift IN ('1 смена', '2 смена'))
);

CREATE TABLE "staffing_plans" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "work_date" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "subobject_id" BIGINT NOT NULL,
    "planned_count" BIGINT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (planned_count >= 0)
);

CREATE TABLE "staffing_row_details" (
    "worker_id" BIGINT NOT NULL,
    "brigadier_override" TEXT,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "linear_itr_override" TEXT,
    "linear_itr_person_id" BIGINT,
    "brigadier_person_id" BIGINT,
    "linear_itr_worker_id" BIGINT,
    "brigadier_worker_id" BIGINT,
    PRIMARY KEY ("worker_id")
);

CREATE TABLE "staffing_shifts" (
    "work_date" TEXT NOT NULL,
    "worker_id" BIGINT NOT NULL,
    "shift" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("work_date", "worker_id"),
    CHECK (shift IN ('1 смена', '2 смена'))
);

CREATE TABLE "subobjects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "object_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "telegram_link_codes" (
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    PRIMARY KEY ("token_hash")
);

CREATE TABLE "telegram_links" (
    "user_id" BIGINT NOT NULL,
    "bot_id" BIGINT NOT NULL,
    "telegram_user_id" BIGINT NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "linked_at" BIGINT NOT NULL,
    PRIMARY KEY ("user_id")
);

CREATE TABLE "telegram_requests" (
    "bot_id" BIGINT NOT NULL,
    "update_id" BIGINT NOT NULL,
    "user_id" BIGINT,
    "received_at" BIGINT NOT NULL,
    "state" TEXT NOT NULL,
    PRIMARY KEY ("bot_id", "update_id")
);

CREATE TABLE "telegram_state" (
    "bot_id" BIGINT NOT NULL,
    "next_offset" BIGINT NOT NULL DEFAULT 0,
    "polled_at" BIGINT NOT NULL DEFAULT 0,
    "error" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY ("bot_id")
);

CREATE TABLE "user_activity_meta" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "started_at" BIGINT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (id = 1)
);

CREATE TABLE "user_profiles" (
    "user_id" BIGINT NOT NULL,
    "phone" TEXT NOT NULL DEFAULT '',
    "email" TEXT NOT NULL DEFAULT '',
    "contact" TEXT NOT NULL DEFAULT '',
    "shortcuts_json" TEXT NOT NULL DEFAULT '{}',
    "shortcuts_enabled" BIGINT NOT NULL DEFAULT 1,
    "edit_token" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("user_id")
);

CREATE TABLE "user_sessions" (
    "session_key" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "logged_in_at" BIGINT,
    "last_seen_at" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "ended_at" BIGINT,
    PRIMARY KEY ("session_key")
);

CREATE TABLE "user_smu_access" (
    "user_id" BIGINT NOT NULL,
    "mode" TEXT NOT NULL,
    "departments_json" TEXT NOT NULL,
    "edit_token" TEXT NOT NULL,
    "updated_by" BIGINT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("user_id"),
    CHECK (mode IN ('all', 'selected'))
);

CREATE TABLE "user_smu_access_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "before_json" TEXT NOT NULL,
    "after_json" TEXT NOT NULL,
    "changed_by" BIGINT NOT NULL,
    "changed_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user_staffing_preferences" (
    "user_id" BIGINT NOT NULL,
    "settings_json" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("user_id")
);

CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" CITEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "active" BIGINT NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id"),
    CHECK (role IN ('super_admin', 'admin', 'foreman', 'viewer', 'hr_viewer'))
);

CREATE TABLE "workers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "full_name" TEXT NOT NULL,
    "personnel_no" CITEXT NOT NULL,
    "contractor" TEXT NOT NULL DEFAULT '',
    "employer" TEXT NOT NULL DEFAULT '',
    "profession" TEXT NOT NULL DEFAULT '',
    "active" BIGINT NOT NULL DEFAULT 1,
    "category" TEXT NOT NULL DEFAULT '',
    "department" TEXT NOT NULL DEFAULT '',
    "gsp_profession" TEXT NOT NULL DEFAULT '',
    "pps" TEXT NOT NULL DEFAULT '',
    PRIMARY KEY ("id")
);

CREATE INDEX idx_assignments_crew_date ON assignments(crew_id NULLS FIRST, work_date NULLS FIRST);

CREATE INDEX idx_assignments_dashboard ON assignments(work_date NULLS FIRST, shift NULLS FIRST, subobject_id NULLS FIRST, employer NULLS FIRST);

CREATE INDEX idx_assignments_date ON assignments(work_date NULLS FIRST);

CREATE UNIQUE INDEX "uq_assignments_3" ON "assignments" ("work_date", "shift", "worker_id");

CREATE UNIQUE INDEX "uq_contractors_0" ON "contractors" ("name_key");

CREATE UNIQUE INDEX "uq_crew_members_1" ON "crew_members" ("worker_id");

CREATE UNIQUE INDEX idx_crew_import_key ON crews(import_key NULLS FIRST) WHERE NOT import_key IS NULL;

CREATE UNIQUE INDEX "uq_crews_1" ON "crews" ("owner_user_id", "name");

CREATE INDEX idx_daily_plans_date ON daily_staffing_plans(work_date NULLS FIRST);

CREATE INDEX idx_employee_contractors_contractor ON employee_contractors(contractor_id NULLS FIRST);

CREATE INDEX idx_employee_gdlr_category ON employee_gdlr(category_id NULLS FIRST);

CREATE INDEX idx_employee_restorations_worker ON employee_restorations(worker_id NULLS FIRST, id NULLS FIRST);

CREATE UNIQUE INDEX "uq_employee_restorations_1" ON "employee_restorations" ("edit_token");

CREATE INDEX idx_employee_smu_catalog ON employee_smu(smu_id NULLS FIRST);

CREATE UNIQUE INDEX "uq_gdlr_categories_0" ON "gdlr_categories" ("name_key");

CREATE UNIQUE INDEX "uq_location_stages_0" ON "location_stages" ("name");

CREATE UNIQUE INDEX "uq_manual_employees_0" ON "manual_employees" ("request_key");

CREATE UNIQUE INDEX "uq_objects_0" ON "objects" ("name");

CREATE UNIQUE INDEX "uq_outstaff_imports_0" ON "outstaff_imports" ("request_key");

CREATE UNIQUE INDEX "uq_outstaff_members_0" ON "outstaff_members" ("identity_key");

CREATE INDEX idx_placement_verifications_date ON placement_verifications(work_date NULLS FIRST);

CREATE INDEX idx_smu_aliases_catalog ON smu_aliases(smu_id NULLS FIRST);

CREATE UNIQUE INDEX "uq_smu_catalog_0" ON "smu_catalog" ("name");

CREATE INDEX idx_staffing_history_user ON staffing_action_history(user_id NULLS FIRST, state NULLS FIRST, id NULLS FIRST);

CREATE UNIQUE INDEX "uq_staffing_imports_0" ON "staffing_imports" ("sha256");

CREATE UNIQUE INDEX "uq_staffing_people_0" ON "staffing_people" ("import_id", "source_row");

CREATE INDEX idx_staffing_plans_date_shift ON staffing_plans(work_date NULLS FIRST, shift NULLS FIRST, subobject_id NULLS FIRST);

CREATE UNIQUE INDEX "uq_staffing_plans_1" ON "staffing_plans" ("work_date", "shift", "subobject_id");

CREATE INDEX idx_subobjects_object ON subobjects(object_id NULLS FIRST);

CREATE UNIQUE INDEX "uq_subobjects_1" ON "subobjects" ("object_id", "name");

CREATE UNIQUE INDEX "uq_telegram_link_codes_0" ON "telegram_link_codes" ("user_id");

CREATE UNIQUE INDEX "uq_telegram_links_0" ON "telegram_links" ("bot_id", "telegram_user_id");

CREATE INDEX idx_user_sessions_presence ON user_sessions(last_seen_at NULLS FIRST) WHERE ended_at IS NULL;

CREATE INDEX idx_user_sessions_user ON user_sessions(user_id NULLS FIRST, logged_in_at NULLS FIRST);

CREATE INDEX idx_user_sessions_login ON user_sessions(logged_in_at NULLS FIRST, user_id NULLS FIRST);

CREATE UNIQUE INDEX "uq_users_0" ON "users" ("username");

CREATE UNIQUE INDEX "uq_workers_0" ON "workers" ("personnel_no");

ALTER TABLE "assignment_events" ADD CONSTRAINT "fk_assignment_events_0" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignment_events" ADD CONSTRAINT "fk_assignment_events_1" FOREIGN KEY ("after_subobject_id") REFERENCES "subobjects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignment_events" ADD CONSTRAINT "fk_assignment_events_2" FOREIGN KEY ("before_subobject_id") REFERENCES "subobjects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignment_events" ADD CONSTRAINT "fk_assignment_events_3" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignment_events" ADD CONSTRAINT "fk_assignment_events_4" FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignments_0" FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignments_1" FOREIGN KEY ("foreman_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignments_2" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "assignments" ADD CONSTRAINT "fk_assignments_3" FOREIGN KEY ("subobject_id") REFERENCES "subobjects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "contractors" ADD CONSTRAINT "fk_contractors_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crew_members" ADD CONSTRAINT "fk_crew_members_0" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crew_members" ADD CONSTRAINT "fk_crew_members_1" FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crews" ADD CONSTRAINT "fk_crews_0" FOREIGN KEY ("brigadier_worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crews" ADD CONSTRAINT "fk_crews_1" FOREIGN KEY ("linear_itr_worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crews" ADD CONSTRAINT "fk_crews_2" FOREIGN KEY ("brigadier_person_id") REFERENCES "staffing_people" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crews" ADD CONSTRAINT "fk_crews_3" FOREIGN KEY ("linear_itr_person_id") REFERENCES "staffing_people" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "crews" ADD CONSTRAINT "fk_crews_4" FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "daily_staffing_plans" ADD CONSTRAINT "fk_daily_staffing_plans_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "daily_staffing_plans" ADD CONSTRAINT "fk_daily_staffing_plans_1" FOREIGN KEY ("subobject_id") REFERENCES "subobjects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_contractors" ADD CONSTRAINT "fk_employee_contractors_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_contractors" ADD CONSTRAINT "fk_employee_contractors_1" FOREIGN KEY ("contractor_id") REFERENCES "contractors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_contractors" ADD CONSTRAINT "fk_employee_contractors_2" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_employers" ADD CONSTRAINT "fk_employee_employers_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_employers" ADD CONSTRAINT "fk_employee_employers_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_gdlr" ADD CONSTRAINT "fk_employee_gdlr_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_gdlr" ADD CONSTRAINT "fk_employee_gdlr_1" FOREIGN KEY ("category_id") REFERENCES "gdlr_categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_gdlr" ADD CONSTRAINT "fk_employee_gdlr_2" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_removals" ADD CONSTRAINT "fk_employee_removals_0" FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_removals" ADD CONSTRAINT "fk_employee_removals_1" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_removals" ADD CONSTRAINT "fk_employee_removals_2" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_restorations" ADD CONSTRAINT "fk_employee_restorations_0" FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_restorations" ADD CONSTRAINT "fk_employee_restorations_1" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_restorations" ADD CONSTRAINT "fk_employee_restorations_2" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_smu" ADD CONSTRAINT "fk_employee_smu_0" FOREIGN KEY ("smu_id") REFERENCES "smu_catalog" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "employee_smu" ADD CONSTRAINT "fk_employee_smu_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "gdlr_categories" ADD CONSTRAINT "fk_gdlr_categories_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "location_revisions" ADD CONSTRAINT "fk_location_revisions_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "manual_employees" ADD CONSTRAINT "fk_manual_employees_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "manual_employees" ADD CONSTRAINT "fk_manual_employees_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "manual_staffing_people" ADD CONSTRAINT "fk_manual_staffing_people_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "manual_staffing_people" ADD CONSTRAINT "fk_manual_staffing_people_1" FOREIGN KEY ("person_id") REFERENCES "staffing_people" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "objects" ADD CONSTRAINT "fk_objects_0" FOREIGN KEY ("stage_id") REFERENCES "location_stages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "outstaff_import_rows" ADD CONSTRAINT "fk_outstaff_import_rows_0" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "outstaff_import_rows" ADD CONSTRAINT "fk_outstaff_import_rows_1" FOREIGN KEY ("import_id") REFERENCES "outstaff_imports" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "outstaff_imports" ADD CONSTRAINT "fk_outstaff_imports_0" FOREIGN KEY ("imported_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "outstaff_members" ADD CONSTRAINT "fk_outstaff_members_0" FOREIGN KEY ("import_id") REFERENCES "outstaff_imports" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "outstaff_members" ADD CONSTRAINT "fk_outstaff_members_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "placement_verification_events" ADD CONSTRAINT "fk_placement_verification_events_0" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "placement_verifications" ADD CONSTRAINT "fk_placement_verifications_0" FOREIGN KEY ("verified_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "smu_aliases" ADD CONSTRAINT "fk_smu_aliases_0" FOREIGN KEY ("smu_id") REFERENCES "smu_catalog" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "smu_catalog" ADD CONSTRAINT "fk_smu_catalog_0" FOREIGN KEY ("site_chief_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "smu_catalog" ADD CONSTRAINT "fk_smu_catalog_1" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_action_history" ADD CONSTRAINT "fk_staffing_action_history_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_attendance" ADD CONSTRAINT "fk_staffing_attendance_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_attendance" ADD CONSTRAINT "fk_staffing_attendance_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_day_inheritance" ADD CONSTRAINT "fk_staffing_day_inheritance_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_history_replays" ADD CONSTRAINT "fk_staffing_history_replays_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_history_replays" ADD CONSTRAINT "fk_staffing_history_replays_1" FOREIGN KEY ("action_id") REFERENCES "staffing_action_history" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_import_members" ADD CONSTRAINT "fk_staffing_import_members_0" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_import_members" ADD CONSTRAINT "fk_staffing_import_members_1" FOREIGN KEY ("import_id") REFERENCES "staffing_imports" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_imports" ADD CONSTRAINT "fk_staffing_imports_0" FOREIGN KEY ("imported_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_inherited_rows" ADD CONSTRAINT "fk_staffing_inherited_rows_0" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_people" ADD CONSTRAINT "fk_staffing_people_0" FOREIGN KEY ("import_id") REFERENCES "staffing_imports" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_performed_work" ADD CONSTRAINT "fk_staffing_performed_work_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_performed_work" ADD CONSTRAINT "fk_staffing_performed_work_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_plans" ADD CONSTRAINT "fk_staffing_plans_0" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_plans" ADD CONSTRAINT "fk_staffing_plans_1" FOREIGN KEY ("subobject_id") REFERENCES "subobjects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_0" FOREIGN KEY ("brigadier_worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_1" FOREIGN KEY ("linear_itr_worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_2" FOREIGN KEY ("brigadier_person_id") REFERENCES "staffing_people" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_3" FOREIGN KEY ("linear_itr_person_id") REFERENCES "staffing_people" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_4" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_row_details" ADD CONSTRAINT "fk_staffing_row_details_5" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_shifts" ADD CONSTRAINT "fk_staffing_shifts_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staffing_shifts" ADD CONSTRAINT "fk_staffing_shifts_1" FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "subobjects" ADD CONSTRAINT "fk_subobjects_0" FOREIGN KEY ("object_id") REFERENCES "objects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "telegram_link_codes" ADD CONSTRAINT "fk_telegram_link_codes_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "telegram_links" ADD CONSTRAINT "fk_telegram_links_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_profiles" ADD CONSTRAINT "fk_user_profiles_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_sessions" ADD CONSTRAINT "fk_user_sessions_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_smu_access" ADD CONSTRAINT "fk_user_smu_access_0" FOREIGN KEY ("updated_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_smu_access" ADD CONSTRAINT "fk_user_smu_access_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_smu_access_events" ADD CONSTRAINT "fk_user_smu_access_events_0" FOREIGN KEY ("changed_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_smu_access_events" ADD CONSTRAINT "fk_user_smu_access_events_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "user_staffing_preferences" ADD CONSTRAINT "fk_user_staffing_preferences_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
