-- Append-only report history; does not close days or modify staffing facts.
CREATE TABLE report_closure_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_key TEXT NOT NULL, scope_json TEXT NOT NULL,
    work_date TEXT NOT NULL, base_version_id BIGINT,
    fingerprint TEXT NOT NULL, snapshot_json TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id), actor_json TEXT NOT NULL,
    created_at TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL,
    UNIQUE(created_by,idempotency_key)
);
CREATE INDEX idx_report_checks_scope_date ON report_closure_checks(scope_key,work_date,id);
CREATE TABLE report_closure_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_key TEXT NOT NULL, scope_json TEXT NOT NULL,
    work_date TEXT NOT NULL, version INTEGER NOT NULL CHECK(version > 0),
    check_id BIGINT NOT NULL UNIQUE REFERENCES report_closure_checks(id),
    previous_version_id BIGINT REFERENCES report_closure_versions(id),
    correction_reason TEXT NOT NULL,
    fingerprint TEXT NOT NULL, snapshot_json TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id), actor_json TEXT NOT NULL,
    created_at TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL,
    UNIQUE(scope_key,work_date,version), UNIQUE(created_by,idempotency_key),
    CHECK((version=1 AND previous_version_id IS NULL AND correction_reason='') OR
          (version>1 AND previous_version_id IS NOT NULL AND length(trim(correction_reason))>0))
);
ALTER TABLE report_closure_checks ADD CONSTRAINT report_checks_base_version_fk
    FOREIGN KEY(base_version_id) REFERENCES report_closure_versions(id);
CREATE INDEX idx_report_versions_scope_date ON report_closure_versions(scope_key,work_date,id);
CREATE FUNCTION reject_report_closure_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Report checks and versions are immutable' USING ERRCODE='integrity_constraint_violation';
END;
$$;
CREATE TRIGGER immutable_report_checks BEFORE UPDATE OR DELETE OR TRUNCATE
    ON report_closure_checks FOR EACH STATEMENT EXECUTE FUNCTION reject_report_closure_mutation();
CREATE TRIGGER immutable_report_versions BEFORE UPDATE OR DELETE OR TRUNCATE
    ON report_closure_versions FOR EACH STATEMENT EXECUTE FUNCTION reject_report_closure_mutation();
