-- Separate monthly SMG plans; existing daily staffing plans are unchanged.
CREATE TABLE gdlr_hierarchy_nodes (
 id TEXT PRIMARY KEY,
 parent_id TEXT REFERENCES gdlr_hierarchy_nodes(id),
 label TEXT NOT NULL,
 name_key TEXT NOT NULL UNIQUE,
 is_group BOOLEAN NOT NULL,
 sort_order INTEGER NOT NULL,
 category_id BIGINT UNIQUE REFERENCES gdlr_categories(id) ON DELETE SET NULL
);
CREATE TABLE smg_plan_versions (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 scope TEXT NOT NULL,
 period DATE NOT NULL CHECK(EXTRACT(DAY FROM period)=1),
 version INTEGER NOT NULL CHECK(version>0),
 previous_id UUID REFERENCES smg_plan_versions(id),
 source JSONB NOT NULL,
 created_by BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 request_key UUID NOT NULL,
 UNIQUE(scope,period,version),
 UNIQUE(created_by,request_key)
);
CREATE TABLE smg_plan_values (
 version_id UUID NOT NULL REFERENCES smg_plan_versions(id),
 node_id TEXT NOT NULL REFERENCES gdlr_hierarchy_nodes(id),
 value NUMERIC NOT NULL CHECK(value>=0 AND value<=100000000),
 PRIMARY KEY(version_id,node_id)
);
CREATE INDEX smg_plan_latest ON smg_plan_versions(scope,period,version DESC);
GRANT SELECT,INSERT ON smg_plan_versions,smg_plan_values TO workforce_app;
GRANT SELECT,UPDATE ON gdlr_hierarchy_nodes TO workforce_app;
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-bc309d972a3d8c1d',NULL,'Итого','итого',TRUE,3,(SELECT id FROM gdlr_categories WHERE name_key='итого'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d1612b11e3fa6049','gdlr-bc309d972a3d8c1d','Рабочие','рабочие',TRUE,4,(SELECT id FROM gdlr_categories WHERE name_key='рабочие'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d1e9cef2da63870e','gdlr-d1612b11e3fa6049','Основные рабочие','основные рабочие',TRUE,5,(SELECT id FROM gdlr_categories WHERE name_key='основные рабочие'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-c0dd4799691a8e80','gdlr-d1e9cef2da63870e','Бетонщик','бетонщик',FALSE,6,(SELECT id FROM gdlr_categories WHERE name_key='бетонщик'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-974e118ebb11a5ff','gdlr-d1e9cef2da63870e','Арматурщик','арматурщик',FALSE,7,(SELECT id FROM gdlr_categories WHERE name_key='арматурщик'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-f6b6fae6403e5ba3','gdlr-d1e9cef2da63870e','Электромонтажник','электромонтажник',FALSE,8,(SELECT id FROM gdlr_categories WHERE name_key='электромонтажник'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-06a5872ce52bcd2d','gdlr-d1e9cef2da63870e','Антикоррозийщик','антикоррозийщик',FALSE,9,(SELECT id FROM gdlr_categories WHERE name_key='антикоррозийщик'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-213de616b8901eb6','gdlr-d1e9cef2da63870e','Изолировщик','изолировщик',FALSE,10,(SELECT id FROM gdlr_categories WHERE name_key='изолировщик'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-996cc058822196f8','gdlr-d1e9cef2da63870e','Монтажник СиЖБК','монтажник сижбк',FALSE,11,(SELECT id FROM gdlr_categories WHERE name_key='монтажник сижбк'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-2fe00ec9c9ebe495','gdlr-d1e9cef2da63870e','Монтажник ТТ','монтажник тт',FALSE,12,(SELECT id FROM gdlr_categories WHERE name_key='монтажник тт'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-28fa1e2a5a446e0d','gdlr-d1e9cef2da63870e','Прочие монтажники','прочие монтажники',FALSE,13,(SELECT id FROM gdlr_categories WHERE name_key='прочие монтажники'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-ce18d3cbd3931c4b','gdlr-d1e9cef2da63870e','Сварщик МК','сварщик мк',FALSE,14,(SELECT id FROM gdlr_categories WHERE name_key='сварщик мк'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-70901ad37ddea4d9','gdlr-d1e9cef2da63870e','Сварщик ТТ','сварщик тт',FALSE,15,(SELECT id FROM gdlr_categories WHERE name_key='сварщик тт'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-78e2513e96880af4','gdlr-d1e9cef2da63870e','Сварщик АиПАМ','сварщик аипам',FALSE,16,(SELECT id FROM gdlr_categories WHERE name_key='сварщик аипам'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-7e1eac56e86d0ba9','gdlr-d1e9cef2da63870e','Прочие сварщики и газорезчики','прочие сварщики и газорезчики',FALSE,17,(SELECT id FROM gdlr_categories WHERE name_key='прочие сварщики и газорезчики'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-9967aae483ae0a7c','gdlr-d1e9cef2da63870e','Дефектоскописты','дефектоскописты',FALSE,18,(SELECT id FROM gdlr_categories WHERE name_key='дефектоскописты'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-bb546b99b5f929cc','gdlr-d1e9cef2da63870e','Прочие основные рабочие','прочие основные рабочие',FALSE,19,(SELECT id FROM gdlr_categories WHERE name_key='прочие основные рабочие'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-f9e97861e773b774','gdlr-d1612b11e3fa6049','Водители и механизаторы','водители и механизаторы',TRUE,20,(SELECT id FROM gdlr_categories WHERE name_key='водители и механизаторы'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b4eaa1083efcc10d','gdlr-f9e97861e773b774','Водители','водители',TRUE,21,(SELECT id FROM gdlr_categories WHERE name_key='водители'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-18e0ea8848a59ddb','gdlr-b4eaa1083efcc10d','Водитель грузового автомобиля','водитель грузового автомобиля',FALSE,22,(SELECT id FROM gdlr_categories WHERE name_key='водитель грузового автомобиля'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-8bce5bdf570e91cd','gdlr-b4eaa1083efcc10d','Водитель самосвала','водитель самосвала',FALSE,23,(SELECT id FROM gdlr_categories WHERE name_key='водитель самосвала'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-e7d12529954567d9','gdlr-b4eaa1083efcc10d','Водитель трубоплетевоза','водитель трубоплетевоза',FALSE,24,(SELECT id FROM gdlr_categories WHERE name_key='водитель трубоплетевоза'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-4d5dd454c71b98f1','gdlr-b4eaa1083efcc10d','Водитель вахты','водитель вахты',FALSE,25,(SELECT id FROM gdlr_categories WHERE name_key='водитель вахты'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-c0ad6255bce8e94e','gdlr-b4eaa1083efcc10d','Водитель спецавтотранспорта','водитель спецавтотранспорта',FALSE,26,(SELECT id FROM gdlr_categories WHERE name_key='водитель спецавтотранспорта'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-a727425e980fcf05','gdlr-b4eaa1083efcc10d','Прочие водители','прочие водители',FALSE,27,(SELECT id FROM gdlr_categories WHERE name_key='прочие водители'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-8e24331b026f8d50','gdlr-f9e97861e773b774','Машинисты','машинисты',TRUE,28,(SELECT id FROM gdlr_categories WHERE name_key='машинисты'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b097e5755d18026e','gdlr-8e24331b026f8d50','Машинист бульдозера','машинист бульдозера',FALSE,29,(SELECT id FROM gdlr_categories WHERE name_key='машинист бульдозера'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-e03f61a4a1a8e798','gdlr-8e24331b026f8d50','Машинист трубоукладчика','машинист трубоукладчика',FALSE,30,(SELECT id FROM gdlr_categories WHERE name_key='машинист трубоукладчика'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-2360c01e3736d887','gdlr-8e24331b026f8d50','Машинист крана','машинист крана',FALSE,31,(SELECT id FROM gdlr_categories WHERE name_key='машинист крана'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0e8f77aafa83c931','gdlr-8e24331b026f8d50','Машинист буровой установки','машинист буровой установки',FALSE,32,(SELECT id FROM gdlr_categories WHERE name_key='машинист буровой установки'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-bd2f741de6a51b0e','gdlr-8e24331b026f8d50','Машинист оборудования','машинист оборудования',FALSE,33,(SELECT id FROM gdlr_categories WHERE name_key='машинист оборудования'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b85a19deb1c09973','gdlr-8e24331b026f8d50','Машинист экскаватора','машинист экскаватора',FALSE,34,(SELECT id FROM gdlr_categories WHERE name_key='машинист экскаватора'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-5cdb530f19c5d056','gdlr-8e24331b026f8d50','Машинист АПС','машинист апс',FALSE,35,(SELECT id FROM gdlr_categories WHERE name_key='машинист апс'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-ef2d2d98e4d32cf0','gdlr-8e24331b026f8d50','Прочие машинисты','прочие машинисты',FALSE,36,(SELECT id FROM gdlr_categories WHERE name_key='прочие машинисты'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b3bf2b914c8047d3','gdlr-bc309d972a3d8c1d','ИТР','итр',TRUE,37,(SELECT id FROM gdlr_categories WHERE name_key='итр'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-aa7a380d5d3c518f','gdlr-b3bf2b914c8047d3','Руководители','руководители',TRUE,38,(SELECT id FROM gdlr_categories WHERE name_key='руководители'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-e7fa487bff222b99','gdlr-aa7a380d5d3c518f','Начальник ОП/ рег.управления','начальник оп/ рег.управления',FALSE,39,(SELECT id FROM gdlr_categories WHERE name_key='начальник оп/ рег.управления'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-82e28e9696e1becd','gdlr-aa7a380d5d3c518f','Руководитель проекта, Главный инженер проекта, Заместитель начальника ОП/ рег.управления','руководитель проекта, главный инженер проекта, заместитель начальника оп/ рег.управления',FALSE,40,(SELECT id FROM gdlr_categories WHERE name_key='руководитель проекта, главный инженер проекта, заместитель начальника оп/ рег.управления'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-64bca7d1f5632042','gdlr-aa7a380d5d3c518f','Начальник управления/ СМУ/ КТП/ мех. колонны, Главн. энергетик/ сварщик/ геодезист/ механик, зам. руководителя проекта/ главного инженера проекта','начальник управления/ сму/ ктп/ мех. колонны, главн. энергетик/ сварщик/ геодезист/ механик, зам. руководителя проекта/ главного инженера проекта',FALSE,41,(SELECT id FROM gdlr_categories WHERE name_key='начальник управления/ сму/ ктп/ мех. колонны, главн. энергетик/ сварщик/ геодезист/ механик, зам. руководителя проекта/ главного инженера проекта'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-9eee89634f54afe8','gdlr-aa7a380d5d3c518f','Начальник участка/ отдела/ службы/ автоколонны, зам. нач. управления/ СМУ/ КТП/ мех. колонны, зам. главн. энергетика/ сварщика/ геодезиста/ механика','начальник участка/ отдела/ службы/ автоколонны, зам. нач. управления/ сму/ ктп/ мех. колонны, зам. главн. энергетика/ сварщика/ геодезиста/ механика',FALSE,42,(SELECT id FROM gdlr_categories WHERE name_key='начальник участка/ отдела/ службы/ автоколонны, зам. нач. управления/ сму/ ктп/ мех. колонны, зам. главн. энергетика/ сварщика/ геодезиста/ механика'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-7c06459bf9c6f9bd','gdlr-aa7a380d5d3c518f','Прочие руководители (руководитель группы, зам. начальника участка/ отдела/ службы и пр.)','прочие руководители (руководитель группы, зам. начальника участка/ отдела/ службы и пр.)',FALSE,43,(SELECT id FROM gdlr_categories WHERE name_key='прочие руководители (руководитель группы, зам. начальника участка/ отдела/ службы и пр.)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-99922894b187c6ea','gdlr-b3bf2b914c8047d3','Специалисты и служащие','специалисты и служащие',TRUE,44,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-bd695238f98ee0e8','gdlr-99922894b187c6ea','Геодезическая служба','геодезическая служба',FALSE,45,(SELECT id FROM gdlr_categories WHERE name_key='геодезическая служба'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-cd83b6b9014c9799','gdlr-99922894b187c6ea','Организация и контроль производства','организация и контроль производства',FALSE,46,(SELECT id FROM gdlr_categories WHERE name_key='организация и контроль производства'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d81f160844606d12','gdlr-99922894b187c6ea','Строительный контроль','строительный контроль',FALSE,47,(SELECT id FROM gdlr_categories WHERE name_key='строительный контроль'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0d17e644e7b8d261','gdlr-99922894b187c6ea','ПТО','пто',FALSE,48,(SELECT id FROM gdlr_categories WHERE name_key='пто'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-31db038e96b126c7','gdlr-99922894b187c6ea','Производственная безопасность','производственная безопасность',FALSE,49,(SELECT id FROM gdlr_categories WHERE name_key='производственная безопасность'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-a01bb4472ed328af','gdlr-99922894b187c6ea','Прочие службы','прочие службы',FALSE,50,(SELECT id FROM gdlr_categories WHERE name_key='прочие службы'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-5301447f680d1992','gdlr-b3bf2b914c8047d3','Линейный ИТР','линейный итр',TRUE,51,(SELECT id FROM gdlr_categories WHERE name_key='линейный итр'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b1e6a2f295dfa7a8','gdlr-5301447f680d1992','Старший прораб','старший прораб',FALSE,52,(SELECT id FROM gdlr_categories WHERE name_key='старший прораб'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-fe13c9e07c8af8c4','gdlr-5301447f680d1992','Прораб','прораб',FALSE,53,(SELECT id FROM gdlr_categories WHERE name_key='прораб'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-da6745854a5a34dc','gdlr-5301447f680d1992','Мастер строительных и монтажных работ','мастер строительных и монтажных работ',FALSE,54,(SELECT id FROM gdlr_categories WHERE name_key='мастер строительных и монтажных работ'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-cf7ced7cd508ab50','gdlr-bc309d972a3d8c1d','Вспомогательные работники','вспомогательные работники',TRUE,55,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные работники'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-795c46042aa35d23','gdlr-cf7ced7cd508ab50','Работники складского хозяйства','работники складского хозяйства',TRUE,56,(SELECT id FROM gdlr_categories WHERE name_key='работники складского хозяйства'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-f1b8ed2218e247e6','gdlr-795c46042aa35d23','Руководители складского хозяйства','руководители складского хозяйства',FALSE,57,(SELECT id FROM gdlr_categories WHERE name_key='руководители складского хозяйства'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b1fdfe95cd3d61cd','gdlr-795c46042aa35d23','Специалисты и служащие складского хозяйства','специалисты и служащие складского хозяйства',FALSE,58,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие складского хозяйства'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-b28541d54ea2b7b9','gdlr-795c46042aa35d23','Вспомогательные рабочие складского хозяйства','вспомогательные рабочие складского хозяйства',FALSE,59,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие складского хозяйства'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-79a9b3c81185b72e','gdlr-cf7ced7cd508ab50','Работники РММ','работники рмм',TRUE,60,(SELECT id FROM gdlr_categories WHERE name_key='работники рмм'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-8d00b77a8b3f1171','gdlr-79a9b3c81185b72e','Руководители РММ','руководители рмм',FALSE,61,(SELECT id FROM gdlr_categories WHERE name_key='руководители рмм'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-accde6e216c7c61d','gdlr-79a9b3c81185b72e','Специалисты и служащие РММ','специалисты и служащие рмм',FALSE,62,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие рмм'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0ed69a19298ae369','gdlr-79a9b3c81185b72e','Вспомогательные рабочие РММ','вспомогательные рабочие рмм',FALSE,63,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие рмм'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0b545fde43c44bb7','gdlr-cf7ced7cd508ab50','Работники лаборатории','работники лаборатории',TRUE,64,(SELECT id FROM gdlr_categories WHERE name_key='работники лаборатории'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-9c2e82c21f236780','gdlr-0b545fde43c44bb7','Руководители лаборатории','руководители лаборатории',FALSE,65,(SELECT id FROM gdlr_categories WHERE name_key='руководители лаборатории'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-20894d10b2081ab3','gdlr-0b545fde43c44bb7','Специалисты и служащие лаборатории','специалисты и служащие лаборатории',FALSE,66,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие лаборатории'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-8131465f2955738d','gdlr-0b545fde43c44bb7','Вспомогательные рабочие лаборатории','вспомогательные рабочие лаборатории',FALSE,67,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие лаборатории'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d66135872125ab12','gdlr-cf7ced7cd508ab50','Работники РБУ','работники рбу',TRUE,68,(SELECT id FROM gdlr_categories WHERE name_key='работники рбу'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-e153bca0c7609295','gdlr-d66135872125ab12','Руководители РБУ','руководители рбу',FALSE,69,(SELECT id FROM gdlr_categories WHERE name_key='руководители рбу'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-de712b7909d52155','gdlr-d66135872125ab12','Специалисты и служащие РБУ','специалисты и служащие рбу',FALSE,70,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие рбу'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-2cbb7a95f3664855','gdlr-d66135872125ab12','Вспомогательные рабочие РБУ','вспомогательные рабочие рбу',FALSE,71,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие рбу'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-f7b32e38ce544992','gdlr-cf7ced7cd508ab50','Работники производства кислорода','работники производства кислорода',TRUE,72,(SELECT id FROM gdlr_categories WHERE name_key='работники производства кислорода'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-877f9665ad89168b','gdlr-f7b32e38ce544992','Руководители производства кислорода','руководители производства кислорода',FALSE,73,(SELECT id FROM gdlr_categories WHERE name_key='руководители производства кислорода'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d10f8a14498fbe1e','gdlr-f7b32e38ce544992','Специалисты и служащие производства кислорода','специалисты и служащие производства кислорода',FALSE,74,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие производства кислорода'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-dccb8ae414ee43c0','gdlr-f7b32e38ce544992','Вспомогательные рабочие производства кислорода','вспомогательные рабочие производства кислорода',FALSE,75,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие производства кислорода'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-5fb3c7b26da564a4','gdlr-cf7ced7cd508ab50','Работники производства м/к','работники производства м/к',TRUE,76,(SELECT id FROM gdlr_categories WHERE name_key='работники производства м/к'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-19f819850b85fe8d','gdlr-5fb3c7b26da564a4','Руководители производства м/к','руководители производства м/к',FALSE,77,(SELECT id FROM gdlr_categories WHERE name_key='руководители производства м/к'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-d095c3b8b16b5774','gdlr-5fb3c7b26da564a4','Специалисты и служащие производства м/к','специалисты и служащие производства м/к',FALSE,78,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие производства м/к'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-ee6f96fc500db64e','gdlr-5fb3c7b26da564a4','Вспомогательные рабочие производства м/к','вспомогательные рабочие производства м/к',FALSE,79,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие производства м/к'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-1ba2db9971424270','gdlr-bc309d972a3d8c1d','Обслуживающий персонал','обслуживающий персонал',TRUE,80,(SELECT id FROM gdlr_categories WHERE name_key='обслуживающий персонал'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-9147d41bbb2ee42e','gdlr-1ba2db9971424270','Охрана','охрана',TRUE,81,(SELECT id FROM gdlr_categories WHERE name_key='охрана'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0392c24767ebaa03','gdlr-9147d41bbb2ee42e','Руководители (охрана)','руководители (охрана)',FALSE,82,(SELECT id FROM gdlr_categories WHERE name_key='руководители (охрана)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-198e37a7ae0a52eb','gdlr-9147d41bbb2ee42e','Специалисты и служащие (охрана)','специалисты и служащие (охрана)',FALSE,83,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие (охрана)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-4c92841b7e05a094','gdlr-9147d41bbb2ee42e','Вспомогательные рабочие (охрана)','вспомогательные рабочие (охрана)',FALSE,84,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие (охрана)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-310707447ed9c311','gdlr-1ba2db9971424270','Услуги питания','услуги питания',TRUE,85,(SELECT id FROM gdlr_categories WHERE name_key='услуги питания'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-20e4113d6f1d0c41','gdlr-310707447ed9c311','Руководители (питание)','руководители (питание)',FALSE,86,(SELECT id FROM gdlr_categories WHERE name_key='руководители (питание)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-10a6144d37b51988','gdlr-310707447ed9c311','Специалисты и служащие (питание)','специалисты и служащие (питание)',FALSE,87,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие (питание)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-854dd9cf22a9f439','gdlr-310707447ed9c311','Вспомогательные рабочие (питание)','вспомогательные рабочие (питание)',FALSE,88,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие (питание)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-9ccec50941b3ff83','gdlr-1ba2db9971424270','Обслуживающий персонал на ВЖП','обслуживающий персонал на вжп',TRUE,89,(SELECT id FROM gdlr_categories WHERE name_key='обслуживающий персонал на вжп'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-943911e98ed59b4c','gdlr-9ccec50941b3ff83','Руководители (персонал на ВЖП)','руководители (персонал на вжп)',FALSE,90,(SELECT id FROM gdlr_categories WHERE name_key='руководители (персонал на вжп)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-676b69ba7acb9144','gdlr-9ccec50941b3ff83','Специалисты и служащие (персонал на ВЖП)','специалисты и служащие (персонал на вжп)',FALSE,91,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие (персонал на вжп)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-50fc4bc3a6de5859','gdlr-9ccec50941b3ff83','Вспомогательные рабочие (персонал на ВЖП)','вспомогательные рабочие (персонал на вжп)',FALSE,92,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие (персонал на вжп)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-0516b08416959be2','gdlr-1ba2db9971424270','Медицинский персонал','медицинский персонал',TRUE,93,(SELECT id FROM gdlr_categories WHERE name_key='медицинский персонал'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-dce49ef527ab10f8','gdlr-0516b08416959be2','Руководители (мед. персонал)','руководители (мед. персонал)',FALSE,94,(SELECT id FROM gdlr_categories WHERE name_key='руководители (мед. персонал)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-49772aa207e4a652','gdlr-0516b08416959be2','Специалисты и служащие (мед. персонал)','специалисты и служащие (мед. персонал)',FALSE,95,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие (мед. персонал)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-947f242c04dfc01f','gdlr-0516b08416959be2','Вспомогательные рабочие (мед. персонал)','вспомогательные рабочие (мед. персонал)',FALSE,96,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие (мед. персонал)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-3248061b4d1b52e7','gdlr-1ba2db9971424270','Работники электроснабжения','работники электроснабжения',TRUE,97,(SELECT id FROM gdlr_categories WHERE name_key='работники электроснабжения'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-3152e4bcc2630b38','gdlr-3248061b4d1b52e7','Руководители (электроснабжение)','руководители (электроснабжение)',FALSE,98,(SELECT id FROM gdlr_categories WHERE name_key='руководители (электроснабжение)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-33c36d85ae940ea1','gdlr-3248061b4d1b52e7','Специалисты и служащие (электроснабжение)','специалисты и служащие (электроснабжение)',FALSE,99,(SELECT id FROM gdlr_categories WHERE name_key='специалисты и служащие (электроснабжение)'));
INSERT INTO gdlr_hierarchy_nodes(id,parent_id,label,name_key,is_group,sort_order,category_id) VALUES ('gdlr-3faab0bc85c00e33','gdlr-3248061b4d1b52e7','Вспомогательные рабочие (электроснабжение)','вспомогательные рабочие (электроснабжение)',FALSE,100,(SELECT id FROM gdlr_categories WHERE name_key='вспомогательные рабочие (электроснабжение)'));
