-- Explicit PPS -> SMU hierarchy. Existing employee/report facts remain unchanged.
CREATE TABLE pps_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, name_key TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    edit_token TEXT NOT NULL DEFAULT encode(gen_random_bytes(16),'hex'),
    updated_by BIGINT REFERENCES users(id), updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE smu_catalog ADD COLUMN pps_id BIGINT REFERENCES pps_catalog(id);
CREATE INDEX idx_smu_pps ON smu_catalog(pps_id);
INSERT INTO pps_catalog(name,name_key)
SELECT MIN(name),lower(name) FROM (
    SELECT regexp_replace(trim(pps),'^ППС[[:space:]–—-]*([0-9]+)$','ППС-\1','i') name
    FROM workers WHERE trim(COALESCE(pps,''))<>''
    UNION
    SELECT regexp_replace(trim(scope),'^ППС[[:space:]–—-]*([0-9]+)$','ППС-\1','i')
    FROM smg_plan_versions WHERE trim(scope)<>''
) names GROUP BY lower(name);
GRANT SELECT,INSERT,UPDATE,DELETE ON pps_catalog TO workforce_app;
GRANT USAGE,SELECT ON SEQUENCE pps_catalog_id_seq TO workforce_app;
