CREATE TABLE work_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, name_key TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    edit_token TEXT NOT NULL, updated_by BIGINT REFERENCES users(id),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
ALTER TABLE staffing_performed_work ADD COLUMN work_type_id BIGINT REFERENCES work_types(id);
CREATE INDEX idx_staffing_work_type ON staffing_performed_work(work_type_id,work_date);
INSERT INTO work_types(name,name_key,edit_token) VALUES
    ('Монтаж и сварка МК','монтаж и сварка мк',gen_random_uuid()::text),
    ('Электромонтаж','электромонтаж',gen_random_uuid()::text),
    ('Благоустройство','благоустройство',gen_random_uuid()::text);
