-- Organizational units have their own PPS parent. Existing SMU identities remain authoritative.
CREATE TABLE workforce_divisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 500),
    name_key TEXT NOT NULL,
    pps_id BIGINT REFERENCES pps_catalog(id),
    smu_id BIGINT UNIQUE REFERENCES smu_catalog(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT NOT NULL DEFAULT '',
    edit_token UUID NOT NULL DEFAULT gen_random_uuid(),
    updated_by BIGINT REFERENCES users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT(pps_id,name_key)
);
CREATE INDEX idx_workforce_divisions_pps ON workforce_divisions(pps_id);
ALTER TABLE workforce_profiles ADD COLUMN division_id BIGINT REFERENCES workforce_divisions(id);
CREATE INDEX idx_workforce_profiles_division ON workforce_profiles(division_id);
CREATE TRIGGER registry_changed AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON workforce_divisions
    FOR EACH STATEMENT EXECUTE FUNCTION workforce_registry_changed();
CREATE TRIGGER registry_changed AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pps_catalog
    FOR EACH STATEMENT EXECUTE FUNCTION workforce_registry_changed();

INSERT INTO workforce_divisions(name,name_key,pps_id,smu_id,active)
SELECT name,log_casefold(trim(name)),pps_id,id,active=1 FROM smu_catalog;

CREATE FUNCTION sync_smu_division() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
    UPDATE public.workforce_divisions SET name=NEW.name,name_key=public.log_casefold(trim(NEW.name)),
        pps_id=NEW.pps_id,active=NEW.active=1,updated_by=NEW.updated_by,
        edit_token=gen_random_uuid(),updated_at=now() WHERE smu_id=NEW.id;
    IF FOUND THEN RETURN NULL; END IF;
    INSERT INTO public.workforce_divisions(name,name_key,pps_id,smu_id,active,updated_by)
    VALUES (NEW.name,public.log_casefold(trim(NEW.name)),NEW.pps_id,NEW.id,NEW.active=1,NEW.updated_by)
    ON CONFLICT(pps_id,name_key) DO UPDATE SET smu_id=excluded.smu_id,active=excluded.active,
        updated_by=excluded.updated_by,edit_token=gen_random_uuid(),updated_at=now()
        WHERE public.workforce_divisions.smu_id IS NULL;
    IF NOT FOUND THEN RAISE EXCEPTION 'Organizational unit already belongs to another SMU'; END IF;
    RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION sync_smu_division() FROM PUBLIC;
CREATE TRIGGER sync_division AFTER INSERT OR UPDATE OF name,pps_id,active ON smu_catalog
    FOR EACH ROW EXECUTE FUNCTION sync_smu_division();
GRANT SELECT,INSERT,UPDATE,DELETE ON workforce_divisions TO workforce_app;
GRANT USAGE,SELECT ON SEQUENCE workforce_divisions_id_seq TO workforce_app;
