"""Generate a reviewable PostgreSQL baseline from a prepared, read-only SQLite copy.

The generated SQL is committed and used by migration; application startup never
derives or changes its schema. No rows or credentials enter this artifact.
"""
import argparse
from pathlib import Path
import sqlite3

import sqlglot
from sqlglot import exp


def quote(name):
    return '"' + name.replace('"', '""') + '"'


def build(source):
    db = sqlite3.connect(source.resolve().as_uri() + '?mode=ro', uri=True)
    db.row_factory = sqlite3.Row
    tables = db.execute("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
    sql = ['-- Frozen baseline: preserves existing IDs, constraints and history.',
           'CREATE EXTENSION IF NOT EXISTS citext;', 'CREATE EXTENSION IF NOT EXISTS pgcrypto;']
    foreign_keys, indexes = [], []
    for table in tables:
        name = table['name']
        parsed = sqlglot.parse_one(table['sql'], read='sqlite')
        definitions = {column.name: column for column in parsed.find_all(exp.ColumnDef)}
        columns = list(db.execute(f'PRAGMA table_info({quote(name)})'))
        keys = sorted([column for column in columns if column['pk']], key=lambda column: column['pk'])
        parts = []
        for column in columns:
            definition = definitions[column['name']]
            source_type = column['type'].upper()
            types = {'INTEGER': 'BIGINT', 'TEXT': 'TEXT', 'REAL': 'DOUBLE PRECISION', 'BLOB': 'BYTEA'}
            if source_type not in types:
                raise ValueError(f'Unreviewed source type: {name}.{column["name"]}: {source_type}')
            kind = types[source_type]
            if any(isinstance(item, exp.CollateColumnConstraint) for item in definition.walk()):
                kind = 'CITEXT'
            part = f'{quote(column["name"])} {kind}'
            if column['name'] == 'id' and len(keys) == 1 and keys[0]['name'] == 'id' and source_type == 'INTEGER':
                part += ' GENERATED BY DEFAULT AS IDENTITY'
            if column['notnull'] or column['pk']:
                part += ' NOT NULL'
            default = column['dflt_value']
            if default is not None:
                if default.lower().replace(' ', '') == 'lower(hex(randomblob(16)))':
                    default = "encode(gen_random_bytes(16), 'hex')"
                elif default == 'CURRENT_TIMESTAMP' and source_type == 'TEXT':
                    default = "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"
                else:
                    default = sqlglot.parse_one(default, read='sqlite').sql(dialect='postgres', unsupported_level=sqlglot.ErrorLevel.RAISE)
                part += ' DEFAULT ' + default
            parts.append(part)
        if keys:
            parts.append('PRIMARY KEY (' + ', '.join(quote(column['name']) for column in keys) + ')')
        for check in parsed.find_all(exp.CheckColumnConstraint):
            expression = check.this.sql(dialect='postgres', unsupported_level=sqlglot.ErrorLevel.RAISE)
            parts.append('CHECK (' + expression + ')')
        sql.append('CREATE TABLE ' + quote(name) + ' (\n    ' + ',\n    '.join(parts) + '\n);')
        for index in db.execute(f'PRAGMA index_list({quote(name)})'):
            if index['origin'] == 'pk':
                continue
            index_columns = list(db.execute(f'PRAGMA index_info({quote(index["name"])})'))
            original = db.execute('SELECT sql FROM sqlite_master WHERE type=\'index\' AND name=?', (index['name'],)).fetchone()
            if original and original[0]:
                indexes.append(sqlglot.parse_one(original[0], read='sqlite').sql(dialect='postgres', unsupported_level=sqlglot.ErrorLevel.RAISE) + ';')
            else:
                fields = ', '.join(quote(column['name']) for column in index_columns)
                indexes.append('CREATE UNIQUE INDEX ' + quote('uq_' + name + '_' + str(index['seq'])) + ' ON ' + quote(name) + ' (' + fields + ');')
        grouped = {}
        for fk in db.execute(f'PRAGMA foreign_key_list({quote(name)})'):
            grouped.setdefault(fk['id'], []).append(fk)
        for number, group in grouped.items():
            group.sort(key=lambda item: item['seq'])
            first = group[0]
            sources = ', '.join(quote(item['from']) for item in group)
            targets = ', '.join(quote(item['to']) for item in group)
            foreign_keys.append(f'ALTER TABLE {quote(name)} ADD CONSTRAINT {quote("fk_" + name + "_" + str(number))}'
                                f' FOREIGN KEY ({sources}) REFERENCES {quote(first["table"])} ({targets})'
                                f' ON UPDATE {first["on_update"]} ON DELETE {first["on_delete"]} DEFERRABLE INITIALLY DEFERRED;')
    db.close()
    return '\n\n'.join(sql + indexes + foreign_keys) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    if args.output.exists():
        raise SystemExit('Refusing to replace a reviewed baseline.')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build(args.source), encoding='utf-8')
    print('Generated schema; review before applying.')
