"""Freeze Python's Unicode casefold rules for identical log search on both DBs."""
import json
from pathlib import Path
import sys
import unicodedata

mapping = {chr(point): chr(point).casefold() for point in range(sys.maxunicode + 1)
           if chr(point).casefold() != chr(point)}
literal = json.dumps(mapping, ensure_ascii=True, separators=(',', ':')).replace("'", "''")
output = Path(__file__).resolve().parents[1] / 'migrations/postgres/003_casefold.sql'
if output.exists():
    raise SystemExit('Refusing to replace an existing migration.')
output.write_text(f'''-- Unicode {unicodedata.unidata_version}; generated by tools/build_casefold_function.py.
CREATE FUNCTION log_casefold(value TEXT) RETURNS TEXT
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE AS $function$
    SELECT CASE WHEN value ~ '^[[:ascii:]А-Яа-яЁё]*$' THEN
        translate(value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',
                         'abcdefghijklmnopqrstuvwxyzабвгдеёжзийклмнопрстуфхцчшщъыьэюя')
    ELSE (
        SELECT COALESCE(string_agg(COALESCE('{literal}'::jsonb ->> symbol, symbol), '' ORDER BY ordinal), '')
        FROM regexp_split_to_table(value, '') WITH ORDINALITY AS letters(symbol, ordinal)
    ) END
$function$;
''', encoding='utf-8')
print('Generated Unicode casefold function.')
